cask_args appdir: "/Applications"

tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-drivers"

brew "mas"
brew "git"
# brew "git-flow"
# brew "gpg"
# brew "gpg2"
# brew "pinentry-mac"
brew "node"
brew "yarn", args: ['without-node']

# cask "gpg-suite"
# cask "appcleaner"
# cask "cyberduck"
cask "iina"
# cask "prefs-editor"
# cask "sketch"
cask "webtorrent"

cask "java"
cask "docker"
cask "sourcetree"
cask "gitkraken"
cask "jetbrains-toolbox"
cask "sublime-text"
cask "postman"
cask "insomnia"
cask "cheatsheet"
cask "google-chrome-canary"
cask "firefox-developer-edition"

cask "logitech-options"
cask "vlc"
cask "alfred"
cask "notion"
cask "evernote"
cask "tunnelbear"
cask "spotify"
cask "pocket-casts"
cask "slack"
cask "telegram"
cask "the-unarchiver"
cask "calibre"
cask "elmedia-player"
cask "pomodone"
