cask_args appdir: "/Applications"

tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-drivers"

brew "mas"
brew "git"
# brew "git-flow"
brew "gpg"
brew "pinentry-mac"
brew "node"
brew "yarn", args: ['ignore-dependencies']

cask "java"
# cask "docker"
cask "sourcetree"
# cask "gitkraken"
cask "jetbrains-toolbox"
cask "sublime-text"
# cask "postman"
# cask "insomnia"
# cask "cheatsheet"
cask "google-chrome-canary"
# cask "firefox-developer-edition"

# cask "logitech-options"
# cask "vlc"
cask "alfred"
cask "notion"
cask "evernote"
cask "tunnelbear"
cask "spotify"
# cask "pocket-casts"
# cask "slack"
cask "telegram"
cask "the-unarchiver"
cask "calibre"
cask "elmedia-player"
cask "pomodone"
cask "raindropio"
# cask "iina"
cask "webtorrent"
cask "grammarly"
cask "android-file-transfer"
# cask "prefs-editor"
# cask "sketch"
# cask "cyberduck"

## app store apps

mas "Amphetamine", id: 937984704
mas "Todoist", id: 585829637
# mas "App Cleaner", id: 1013897218

# safari extentions

mas "AdGuard for Safari", id: 1440147259
mas "PiPifier", id: 1160374471
mas "1password 7 - Password Manager (7.2.5)", id: 1333542190
